version: '3'

services:
  db:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
  app:
    command: /code/compose/django/runserver.sh
    environment:
      DATABASE_URL: postgis://postgres@db:5432/postgres
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - .:/code
    links:
      - db:db
    ports:
      - "8000:8000"
    depends_on:
      - db
  proxy:
    image: nginx:stable-alpine
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    links:
      - app:app
    volumes:
      - ./frontend:/code
    ports:
      - "8081:80"

volumes:
  pgdata:
